apiVersion: apps/v1
kind: Deployment
metadata:
  name: linear-regression-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linear-regression-app
  template:
    metadata:
      labels:
        app: linear-regression-app
    spec:
      containers:
      - name: linear-regression-container
        image: {{REGION}}-docker.pkg.dev/{{PROJECT_ID}}/{{ARTIFACT_REGISTRY}}/{{model_image}}-cpu-inference:latest
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: linear-regression-service
spec:
  type: LoadBalancer
  selector:
    app: linear-regression-app
  ports:
  - port: 80
    targetPort: 8000
